name: Build artifacts

on:
  push:
    tags:
      - '*'

jobs:
  packages:
    name: "Build packages"
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: prepare runner
      run: |
        sudo snap install snapcraft --classic
  
    - name: install_deps
      run: make install_deps

    - name: build_snap_x64
      run: make build_snap_x64

    # - name: build_snap_arm64 # This step is currently disabled due to issues with snapcraft + arm64 on github runners
    #   run: make build_snap_arm64

    - name: Get the version
      run: echo "version=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_ENV"

    - name: Generate sha256
      run: echo "$(sha256sum artifacts/x64/*.snap)" > sha256

    - name: create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.version }}
        body: 'Update to version ${{ env.version }}'
        draft: false
        files: |
            artifacts/x64/*.snap
            sha256
